version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # for persisting redis data
    command: redis-server --save 60 1 --loglevel warning
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: django_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 FITTR_API.asgi:application
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  huey:
    build:
      context: .
      dockerfile: Dockerfile
      target: huey_worker
    depends_on:
      - redis
      - web
    command: python manage.py run_huey
volumes:
  redis_data: