# Generated by Django 5.1.3 on 2024-12-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.SmallIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("weight", models.SmallIntegerField()),
                ("height", models.SmallIntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FITTR_API.product",
                    ),
                ),
            ],
        ),
    ]
