# Generated by Django 5.1.3 on 2025-01-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FITTR_API", "0003_product_created_at_user_created_at_exercisesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="resistance_characteristic_uuid",
            field=models.CharField(
                default="87654321-4321-4321-4321-abcdef987654", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="service_uuid",
            field=models.CharField(
                default="12345678-1234-1234-1234-123456789abc", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stop_characteristic_uuid",
            field=models.CharField(
                default="87654321-4321-4321-4321-abcdef987654", max_length=50
            ),
        ),
    ]
