# Generated by Django 5.1.3 on 2025-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FITTR_API", "0004_product_resistance_characteristic_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisesession",
            name="duration",
            field=models.FloatField(),
        ),
    ]
