# Generated by Django 5.1.3 on 2025-02-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FITTR_API",
            "0006_rename_resistance_characteristic_uuid_product_left_resistance_characteristic_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fitness_goal",
            field=models.CharField(default="undecided", max_length=30),
        ),
    ]
